integration_tests:
  target: fabric
  outputs:
    fabric:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      port: 1433
      host: "{{ env_var('FABRIC_ENDPOINT') }}"
      database: "{{ env_var('FABRIC_DWH_NAME', 'dwh') }}"
      authentication: cli
      schema: tsql_utils_integration_tests_fabric
