name: "tsql_utils_dbt_date_integration_tests"
version: "1.0"
config-version: 2

profile: "integration_tests"

dispatch:
  - macro_namespace: dbt_utils
    search_order:
      [
        "tsql_utils_dbt_date_integration_tests",
        "tsql_utils",
        "dbt",
        "dbt_utils",
      ]
  - macro_namespace: dbt_date
    search_order:
      ["tsql_utils_dbt_date_integration_tests", "tsql_utils", "dbt", "dbt_date"]

vars:
  "dbt_date:time_zone": "UTC"

models:
  dbt_date_integration_tests:
    schema: dbt_date_integration_tests
    materialized: table
    dim_hour: &disabled # overriden in this project as the default impl uses nested CTEs
      enabled: false
    dim_week: *disabled # overriden in this project as the default impl uses nested CTEs
    dim_date: *disabled # overriden in this project as the default impl uses nested CTEs
    dim_date_fiscal: *disabled # overriden in this project as the default impl uses nested CTEs

data_tests:
  dbt_date_integration_tests:
    expression_is_true_test_dates_rounded_timestamp_utc_dbt_date_round_timestamp_time_stamp_utc_: *disabled
    expression_is_true_test_dates_time_stamp_utc_dbt_date_from_unixtimestamp_unix_epoch_: *disabled
    expression_is_true_test_dates_unix_epoch_dbt_date_to_unixtimestamp_time_stamp_utc_: *disabled