name: "tsql_utils_dbt_utils_integration_tests"
version: "1.0"
config-version: 2

profile: "integration_tests"

dispatch:
  - macro_namespace: dbt_utils
    search_order:
      [
        "tsql_utils_dbt_utils_integration_tests",
        "tsql_utils",
        "dbt",
        "dbt_utils_integration_tests",
        "dbt_utils",
      ]

models:
  dbt_utils_integration_tests:
    index: HEAP # Synapse only
    as_columnstore: "{{ target.type == 'sqlserver' }}"
    enabled: true
    web:
      test_url_host: &disabled
        enabled: false
      test_url_path: *disabled
      test_urls: *disabled
    sql:
      test_generate_series: *disabled
      test_get_column_values: *disabled
      test_get_relations_by_pattern: *disabled
      test_get_relations_by_prefix_and_union: *disabled
      test_groupby: *disabled
      test_union: *disabled
      test_unpivot_bool: *disabled
      test_get_single_value: *disabled
      test_get_single_value_default: *disabled
    
data_tests:
  dbt_utils_integration_tests: *disabled

seeds:
  dbt_utils_integration_tests:
    schema_tests:
      data_test_sequential_timestamps: *disabled
      data_test_mutually_exclusive_ranges_with_gaps_zero_length: *disabled
      data_test_mutually_exclusive_ranges_no_gaps: *disabled
      data_test_mutually_exclusive_ranges_with_gaps: *disabled

    sql:
      data_unpivot_bool: *disabled
      data_unpivot_bool_expected: *disabled
      data_get_single_value: *disabled
